services:
  backend:
    container_name: private-childcare-calendar-api
    build:
      context: .
      dockerfile: ./Dockerfile
    restart: unless-stopped
    volumes:
      - ./Database:/app/database
      - ./Backups:/app/backups
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
    networks:
      - proxy-net

networks:
  proxy-net:
    external: true